using System.Text;

namespace MDC.Core.Services.Providers.MeshCentral;

/// <summary>
/// Renders the cloud-init user-data injected at VM creation time so that each
/// new guest self-enrols into MeshCentral on first boot. The real PVE
/// integration will insert the rendered output into the VM's cloud-init config
/// drive.
/// </summary>
public static class CloudInitTemplate
{
    /// <summary>
    /// Render a user-data YAML blob that installs and registers the MeshCentral
    /// agent under the group for <paramref name="workspaceId"/>.
    /// </summary>
    /// <param name="meshBaseUrl">Base URL of the MeshCentral server (https, no trailing slash).</param>
    /// <param name="workspaceId">Workspace id used as the Mesh device group.</param>
    /// <param name="groupPrefix">Prefix applied to the Mesh group name (e.g. "mdc-ws-").</param>
    /// <param name="vmid">Proxmox VMID — stamped into the agent identity for reconciliation.</param>
    public static string Render(string meshBaseUrl, string workspaceId, string groupPrefix, int vmid)
    {
        var baseUrl = meshBaseUrl.TrimEnd('/');
        var group = $"{groupPrefix}{workspaceId}";
        var sb = new StringBuilder();
        sb.AppendLine("#cloud-config");
        sb.AppendLine($"# Generated by MDC for workspace {workspaceId}, vmid {vmid}");
        sb.AppendLine("packages:");
        sb.AppendLine("  - curl");
        sb.AppendLine("runcmd:");
        sb.AppendLine("  - [ sh, -xc, \"mkdir -p /opt/meshcentral\" ]");
        sb.AppendLine($"  - [ sh, -xc, \"curl -sL {baseUrl}/meshagents?id=6&installflags=2&meshid={group} -o /opt/meshcentral/agent\" ]");
        sb.AppendLine("  - [ sh, -xc, \"chmod +x /opt/meshcentral/agent\" ]");
        sb.AppendLine($"  - [ sh, -xc, \"/opt/meshcentral/agent -install --group={group} --hostid=vmid-{vmid}\" ]");
        sb.AppendLine("  - [ sh, -xc, \"systemctl enable meshagent || true\" ]");
        sb.AppendLine("  - [ sh, -xc, \"systemctl start meshagent || true\" ]");
        return sb.ToString();
    }
}
